"""empty message

Revision ID: 57ef011a95b1
Revises: e1940e3fe146
Create Date: 2023-08-05 17:16:11.367972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ef011a95b1'
down_revision = 'e1940e3fe146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cons', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'consumers', ['cons'], ['cons_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cons')

    # ### end Alembic commands ###
