"""empty message

Revision ID: 7e28791fb5ba
Revises: 
Create Date: 2023-08-05 13:39:01.820420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e28791fb5ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumers',
    sa.Column('cons_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=200), nullable=False),
    sa.Column('c_email', sa.String(length=200), nullable=False),
    sa.Column('c_mobile', sa.String(length=60), nullable=False),
    sa.Column('c_password', sa.String(length=300), nullable=False),
    sa.Column('c_role', sa.String(length=100), nullable=False),
    sa.Column('c_date', sa.DateTime(), nullable=False),
    sa.Column('c_is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cons_id')
    )
    op.create_table('products',
    sa.Column('prod_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('p_name', sa.String(length=200), nullable=False),
    sa.Column('p_type', sa.String(length=100), nullable=False),
    sa.Column('p_price', sa.String(length=300), nullable=False),
    sa.Column('p_desc', sa.String(length=500), nullable=False),
    sa.Column('p_date', sa.DateTime(), nullable=False),
    sa.Column('p_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_table('orders',
    sa.Column('ord_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod', sa.BigInteger(), nullable=True),
    sa.Column('o_mobile', sa.String(length=60), nullable=False),
    sa.Column('pay_status', sa.String(length=300), nullable=False),
    sa.Column('o_status', sa.String(length=300), nullable=False),
    sa.Column('o_addr', sa.String(length=500), nullable=False),
    sa.Column('o_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prod'], ['products.prod_id'], ),
    sa.PrimaryKeyConstraint('ord_id')
    )
    op.create_table('reviews',
    sa.Column('rev_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod', sa.BigInteger(), nullable=True),
    sa.Column('review', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rev_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prod'], ['products.prod_id'], ),
    sa.PrimaryKeyConstraint('rev_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('consumers')
    # ### end Alembic commands ###
