"""empty message

Revision ID: 8a599ceb468d
Revises: 75337791dc53
Create Date: 2023-11-01 10:39:09.527477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a599ceb468d'
down_revision = '75337791dc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('p_tag', sa.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('p_code', sa.String(length=100), nullable=False))
        batch_op.drop_column('p_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('p_code')
        batch_op.drop_column('p_tag')
        batch_op.drop_column('p_category')

    # ### end Alembic commands ###
