"""empty message

Revision ID: c17b43d8016a
Revises: 8a599ceb468d
Create Date: 2023-11-01 11:34:37.969873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17b43d8016a'
down_revision = '8a599ceb468d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.drop_column('c_mobile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_mobile', sa.VARCHAR(length=60), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
