"""empty message

Revision ID: e1940e3fe146
Revises: 7e28791fb5ba
Create Date: 2023-08-05 16:04:29.690807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1940e3fe146'
down_revision = '7e28791fb5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['c_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
